name: Python CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup venv & pip install 
        run: cd python && python3 -m venv .venv && .venv/bin/pip install -r requirements.txt

      - name: run pytest
        run: cd python && .venv/bin/pytest test
